### ISSUE TITLE
As a student, I want to have the ability to view the lessons/assignment requirements side by side while I am working on a coding assignment so that I am able to learn concepts better and apply them to the task.

### ISSUE THREAD

**Issue by julianbeloiu** [The-9-Gs/Sapphire-20-9g#1]
Acceptance Criteria: 
- [x] Students are provided with lessons which are already stored in the database and they are able to view them as they are working on the assignment. 

Tasks:
- [x] Render Lesson View Window on command.
- [x] Allow student to load other lessons, replacing the current lesson.
- [x] Allow student to scale the lesson window horizontally to their liking. (arrows between split bar on wireframes)
- [x] Allow student to close the Lesson View Window with an 'x' at the top right.

**Comment by amaxyza** [comment]
I was able to develop to code that allows for the render of a button that can be used to call upon the lesson load function.

**Comment by DeepCodingStuff** [comment]
I developed code which will be able to hide and open the lesson window within the split screen.

**Comment by evanhadam** [comment]
I developed code that is the base of divider functionality, which will allow student to scale the lesson window horizontally to their liking. (arrows between split bar on wireframes). No issues on sonarcloud yet, but feature isn't 100% functional. 

Acceptance criteria - Successfully adjusts x-position of cut off between two screens 99% of the time.

Wireframe for feature: [https://www.figma.com/file/DxTJsXAKoVJuk1lvhUrK0R/Untitled?type=design&node-id=0%3A1&mode=design&t=r8B7WTCRWR4yy6ib-1](https://www.figma.com/file/DxTJsXAKoVJuk1lvhUrK0R/Untitled?type=design&node-id=0%3A1&mode=design&t=r8B7WTCRWR4yy6ib-1)

**Comment by DeepCodingStuff** [comment]
Updated the hide/open lesson to be compatible with the split screen window - some modifications needed to be made here.

**Comment by evanhadam** [comment]
Finished UI and fixed resizing on button click bug
